# Generated by Django 2.2.9 on 2020-06-17 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgregatorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataverse_id', models.CharField(max_length=120, unique=True, verbose_name='Dataverse Id')),
                ('friendly_name', models.CharField(max_length=120, verbose_name='Nazwa przyjazna')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('order', models.IntegerField(default=1, verbose_name='Kolejność')),
                ('public', models.BooleanField(default=True, verbose_name='Publiczny')),
            ],
        ),
        migrations.CreateModel(
            name='FacetField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facet_field_name', models.CharField(max_length=120, verbose_name='Nazwa pola w Solr')),
                ('facet_field_friendly_name', models.CharField(max_length=120, verbose_name='Nazwa przyjazna')),
                ('order', models.IntegerField(default=1, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Pole filtrowalne',
                'verbose_name_plural': 'Pola filtrowalne',
            },
        ),
        migrations.CreateModel(
            name='FilterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nazwa pola w Dataverse')),
                ('friendly_name', models.CharField(max_length=120, verbose_name='Nazwa przyjazna')),
                ('order', models.IntegerField(default=1, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Grupa pól filtracyjnych',
                'verbose_name_plural': 'Grupy pól filtracyjnych',
            },
        ),
        migrations.CreateModel(
            name='FilterField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=120, unique=True, verbose_name='Nazwa pola w Dataverse')),
                ('field_friendly_name', models.CharField(max_length=120, verbose_name='Nazwa przyjazna')),
                ('title', models.CharField(max_length=120, verbose_name='Tytuł')),
                ('type', models.CharField(max_length=120, verbose_name='Rodzaj pola')),
                ('watermark', models.CharField(max_length=120, verbose_name='Watermark')),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=1, verbose_name='Kolejność')),
                ('public', models.BooleanField(default=True, verbose_name='Publiczny')),
                ('filter_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api.FilterGroup')),
            ],
        ),
    ]
