# Generated by Django 2.2.9 on 2020-08-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterfield',
            name='description',
        ),
        migrations.RemoveField(
            model_name='filterfield',
            name='friendly_name',
        ),
        migrations.RemoveField(
            model_name='filterfield',
            name='title',
        ),
        migrations.RemoveField(
            model_name='filterfield',
            name='type',
        ),
        migrations.RemoveField(
            model_name='filterfield',
            name='watermark',
        ),
    ]
