# Generated by Django 2.2.9 on 2020-05-29 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTagsExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tytuł (nadpisuje podstawowy tytuł)')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Opis (nadpisuje podstawowy opis)')),
                ('keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Keywords')),
                ('author', models.CharField(blank=True, max_length=500, null=True, verbose_name='Autor')),
                ('og_type', models.CharField(blank=True, max_length=15, null=True, verbose_name='Og:Type - według dokumentacji: https://ogp.me/')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
                ('og_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='og_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Miniatura w social Media')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='page_manager.MetaTagsExtension')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
