# Generated by Django 2.2.9 on 2020-10-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutuspage',
            options={'verbose_name': 'Strona o Nas', 'verbose_name_plural': 'Strony o Nas'},
        ),
        migrations.AlterModelOptions(
            name='accordionpage',
            options={'verbose_name': 'Strona z Akordionami', 'verbose_name_plural': 'Strony z Akordionami'},
        ),
    ]
