# Generated by Django 2.2.9 on 2020-08-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_manager', '0003_auto_20200805_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqshort',
            options={'verbose_name': 'Paytanie i odpowiedź', 'verbose_name_plural': 'Pytania i odpowiedzi'},
        ),
    ]
